[2023-02-10 12:32:42,165] [ERROR] => File not found.]
Traceback (most recent call last):
  File "/home/igor/PROJECTS/translate_text/text_translate.py", line 13, in translatios
    with open("inpuot.txt", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'inpuot.txt'
[2023-02-10 12:33:00,749] [ERROR] => File not found.]
Traceback (most recent call last):
  File "/home/igor/PROJECTS/translate_text/text_translate.py", line 13, in translatios
    with open("inpuot.txt", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'inpuot.txt'
[2023-02-10 12:33:26,691] [ERROR] => File not found.]
Traceback (most recent call last):
  File "/home/igor/PROJECTS/translate_text/text_translate.py", line 13, in translatios
    with open("inpuot.txt", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'inpuot.txt'
